---
safe        : true
markdown    : kramdown
highlighter : rouge

#site settings
title       : "Saima Shahid"
name        : &name "Saima Shahid"
description : "Postdoctoral Associate at Donald Danforth Plant Science Center"
url         : shahidsaima.com

#Site author
author:
  name      : "Saima Shahid"
  avatar    : "/images/profile.JPG"
  bio       : "Postdoctoral researcher at Donald Danforth Plant Science Center"
  linkedin  : http://www.linkedin.com/in/saima-shahid/
  google_scholar  : http://scholar.google.com/citations?user=lez4bcIAAAAJ&hl=en
  research_gate  : http://www.researchgate.net/profile/Saima_Shahid/
  orcid     : http://orcid.org/0000-0001-9385-0925
  twitter   : psaima

theme: jekyll-theme-minimal
